export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAILURE = 'LOGIN_FAILURE'

export const START_DOWNLOAD_USERS = 'START_DOWNLOAD_USERS'
export const GET_USERS_SUCCESS = 'GET_USERS_SUCCESS'


export const ONE_USER_SUCCESS = 'ONE_USER_SUCCESS'


export const GET_USER_EDIT = 'GET_USER_EDIT'
export const EDIT_USER_SUCCESS = 'EDIT_USER_SUCCESS'
