export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAILURE = 'LOGIN_FAILURE'

export const START_DOWNLOAD_USERS = 'START_DOWNLOAD_USERS'
export const GET_USERS_SUCCESS = 'GET_USERS_SUCCESS'
